version: '3.8'

services:
  giardini-api:
    build: .
    container_name: giardini-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.giardini-api.rule=Host(`api.giardini.cafe`)"
      - "traefik.http.routers.giardini-api.entrypoints=websecure"
      - "traefik.http.routers.giardini-api.tls.certresolver=mytlschallenge"
      - "traefik.http.services.giardini-api.loadbalancer.server.port=8000"
    networks:
      - n8n_default

networks:
  n8n_default:
    external: true